### ISSUE TITLE
Bug with Neovim

### ISSUE THREAD

**Issue by JackofSpades707** [gioele/vim-autoswap#10]
When using vim it works great, Unfortunately when using neovim however, it doesn't focus on the currently open session (It detects a swap file and alerts me it's opening in read-only mode as if it can't see the other instance of neovim editing the file)

**Comment by gioele** [comment]
Hi @JackofSpades707, thank you for your bug report. I have never used neovim, so I'll have to guess what is going on.

Are you using Mac OS by any chance? The Mac OS part of `vim-autoswap` runs this AppleScript code:

```applescript
tell application "Terminal" to every window whose (
    name begins with "'.shortname.' " and
    name ends with "VIM"
)
```

Maybe the title of the Terminal ends with something different than "VIM".

Could you please check?

**Comment by JackofSpades707** [comment]
Thanks for getting back to me so quickly. :)
I apologize for the lack of context, I am running ArchLinux, kernel : 4.8.13-1-ARCH, here's a copy of my current init.vim (aka ~/.vimrc for neovim)
http://pastie.org/private/hxwxhuxpz97vjybaof8qua#12
(I apologize for it being messy, I do plan on cleaning it up)

**Comment by gioele** [comment]
Hi @JackofSpades707, I think the cause of problem is just that neovim does not enable the `title` option by default, at least in the current stable version (0.1.7). I added some notes to the documentation.

Try enabling `title` with `set title`. Everything should work fine then. If this is not the case, please reopen this issue.

Thank you for the bug report.
