### ISSUE TITLE
HUGE latency (~15s on an 2.3GHz i5 with 16GB RAM)

### ISSUE THREAD

**Issue by rlue** [gioele/vim-autoswap#15]
Hi,

I'm experiencing huge latency as vim-autoswap tries to figure out what to do with an already-open file. (As the title states, lag times are approaching 15 seconds.)

What's more, it only works in Terminal.app (not in MacVim or iTerm), but I suppose that's a separate issue (#11?).

**Comment by gioele** [comment]
Hi @rlue, could you please checkout and use the branch [`verbose-debug`](https://github.com/gioele/vim-autoswap/tree/verbose-debug), then paste here the content of `/tmp/vim-autoswap.log`?

Please use the standard Terminal.app for the moment. We can tackle iTerm support soon after this bug is solved. :)

**Comment by rlue** [comment]
I hate to be that guy, but I can't reproduce the problem anymore. It's strange — I had definitely tried uninstalling and reinstalling a few days ago. Left it uninstalled for a couple days, made a bunch of changes to my vimrc, reinstalled today, and boom, it works. I've even tried reverting to the previous state of my `.vim/` directory, but no luck. :\

In any case, it's quite possible it was the result of a conflict with some other plugin (I have about three dozen installed). I'll keep you posted if the problem crops up again.

---

On an unrelated note, it looks like `verbose-debug` has not been rebased against the latest version of `master` — I received this error, which was [fixed just a week ago](https://github.com/gioele/vim-autoswap/commit/a492e0c0f7f0306a5ad2cfea29d64c4cd7a508eb):

```
Error detected while processing function AS_HandleSwapfile[6]..AS_DetectActiveWindow[11]..AS_DetectActiveWindow_Tmux:
line   11:
E119: Not enough arguments for function: substitute
E15: Invalid expression: substitute(tty[0], '\s\+$', '')
```
