### ISSUE TITLE
"Undefined variable: active_window"

### ISSUE THREAD

**Issue by jpmorris** [gioele/vim-autoswap#6]
I'm getting the following error:

    Error detected while processing function AS_HandleSwapfile..AS_DetectActiveWindow:
    line    8:
    E121: Undefined variable: active_window
    E15: Invalid expression: active_window       

I'm using Vim  7.4.777, windows 7 64bit, installed without admin privileges. I installed the plugin through vundle with a known post-crash swapfile already created.

**Comment by gioele** [comment]
Vim on Windows is not supported by vim-autoswap. If you know a way of retrieving window names and focusing them programmatically, please let me know. Or submit a patch. :)

**Comment by jpmorris** [comment]
Is there a way you could just disable the window swapping feature in windows (and print an error msg, or a prompt: 'are you sure you don't have this open twice?') but keep the automatic if-swap-file-is-older deletion working?

**Comment by gioele** [comment]
You could comment out [the lines dealing with finding the active window](https://github.com/gioele/vim-autoswap/blob/master/plugin/autoswap.vim#L51-L58) and change the first `elseif` into `if`.
